trigger:
- azure

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonarConnect'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'com.petclinic:all:master'
    cliProjectName: 'petclinic'
    cliSources: '.'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=com.petclinic:all:master
      sonar.language=java
      sonar.sources=.
      sonar.tests=.
      sonar.test.inclusions=**/*Test*/**
      sonar.exclusions=**/*Test*/**

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'petclinicTests'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageClassFilter: '**/*Test*/**'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'pom'

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'